### ISSUE TITLE
Also get coverage for pyx file

### ISSUE THREAD

**Issue by tovrstra** [theochem/python-cython-ci-example#12]
See theochem/cellcutoff#4 for an example. Also use && to concatenate bash commands in .travis.yml, to get the right return code.

**Comment by johnyf** [comment]
The approach `coverage xml -i` doesn't work with arbitrary Cython (it probably works here only because the Cython file contains code that is valid Python). See [`coverage.py #601`](https://bitbucket.org/ned/coveragepy/issues/601/cannot-parse-cython-when-creating-xml).

**Comment by tovrstra** [comment]
We have the following in our `.coveraverc` file, which is supposed to make it work:

```
[run]
plugins = Cython.Coverage
```

**Comment by johnyf** [comment]
Thanks a lot for making this observation. I had these lines in my `.coveragerc` under the directory `tests/` (where I run tests of the installed--not in-place built--package). But when trying to collect coverage statistics for Cython files only in-place building works, so I was working outside the `tests` directory, which didn't contain any `.coveragerc`.

Copying the `.coveragerc` to where I run `nosetests` resolved the issue, and `coverage xml` worked without errors.
