### ISSUE TITLE
$TRAVIS_TAG not being set

### ISSUE THREAD

**Issue by matt-chan** [theochem/python-cython-ci-example#18]
@tovrstra No idea what's going on here. 

$TRAVIS_TAG isn't being set on tagged releases so the py36 & osx builds aren't starting. Have you seen this before? It should work for deployments right?

**Comment by tovrstra** [comment]
The problem is that your tag is not named properly. It should be 0.3.2a1. See 

https://travis-ci.org/theochem/python-cython-ci-example/requests

Your tag, 0.3.2a, does not match the branch filter, which is based on PEP440, so please don't change the branch filter.

**Comment by matt-chan** [comment]
Ahh... oops. I didn't know about that page on travis. 

Alright I'll test with the new tag. Hope it works!

**Comment by matt-chan** [comment]
Yep, it's all good, although I found another bug.
